import type { V4Activity } from '../types'
const verified = 'VERIFIED' as const
const needs = 'NEEDS_VERIFICATION' as const
const date = '2026-10-04'

export const coreActivities: V4Activity[] = [
  {id:'v4-steel-bars',name:'Iron + 2 Coal → Steel bar',kind:'PROCESSING',category:'Smithing',skills:['Smithing'],f2p:true,members:true,verified,source:'Migrated from verified V2.x dataset',lastVerified:date,requirements:{skills:[{skill:'Smithing',level:30}]},attention:'MEDIUM',riskType:'SAFE',tags:['steel','bar','smelting','f2p'],items:['Iron ore','Coal','Steel bar'],chain:{acquire:['Iron ore','Coal'],process:['Smelt steel bar'],sell:['Steel bar']}},
  {id:'v4-bait-fishing',name:'Bait fish Sardine / Herring',kind:'GATHERING',category:'Fishing',skills:['Fishing'],f2p:true,members:true,verified,source:'Migrated from verified V2.x dataset + personal measurement',lastVerified:date,requirements:{skills:[{skill:'Fishing',level:10}],gear:['Fishing rod']},attention:'LOW',afkWindowSeconds:45,riskType:'SAFE',competitionRisk:'LOW',tags:['sardine','herring','bait','fishing','f2p'],items:['Raw sardine','Raw herring'],notes:'Personal mixed-output sample exists in V2.5 measurement storage.'},
  {id:'v4-lobster',name:'Fish Lobster (Karamja)',kind:'GATHERING',category:'Fishing',skills:['Fishing'],f2p:true,members:true,verified,source:'Migrated from verified V2.x dataset',lastVerified:date,requirements:{skills:[{skill:'Fishing',level:40}],gear:['Lobster pot'],areas:['Karamja F2P fishing spot']},attention:'LOW',afkWindowSeconds:50,riskType:'SAFE',competitionRisk:'LOW',tags:['lobster','fishing','karamja','f2p'],items:['Raw lobster']},
  {id:'v4-yew',name:'Chop Yew logs',kind:'GATHERING',category:'Woodcutting',skills:['Woodcutting'],f2p:true,members:true,verified,source:'Migrated from verified V2.x dataset',lastVerified:date,requirements:{skills:[{skill:'Woodcutting',level:60}]},attention:'AFK',afkWindowSeconds:60,riskType:'SAFE',competitionRisk:'MEDIUM',tags:['yew','logs','woodcutting','f2p'],items:['Yew logs']},
  {id:'v4-cannonballs',name:'Steel bar → Cannonballs',kind:'PROCESSING',category:'Smithing',skills:['Smithing'],f2p:false,members:true,verified,source:'Migrated from verified V2.5 dataset',lastVerified:date,requirements:{skills:[{skill:'Smithing',level:35}],quests:['Dwarf Cannon'],gear:['Ammo mould']},attention:'AFK',afkWindowSeconds:150,riskType:'SAFE',tags:['cannonball','steel','smithing','members'],items:['Steel bar','Cannonball']},
  {id:'v4-magic-logs',name:'Chop Magic logs',kind:'GATHERING',category:'Woodcutting',skills:['Woodcutting'],f2p:false,members:true,verified,source:'Migrated from verified V2.5 dataset',lastVerified:date,requirements:{skills:[{skill:'Woodcutting',level:75}]},attention:'AFK',afkWindowSeconds:75,riskType:'SAFE',competitionRisk:'LOW',tags:['magic','logs','woodcutting','members'],items:['Magic logs']},
  {id:'v4-sharks',name:'Fish Sharks',kind:'GATHERING',category:'Fishing',skills:['Fishing'],f2p:false,members:true,verified,source:'Migrated from verified V2.5 dataset',lastVerified:date,requirements:{skills:[{skill:'Fishing',level:76}],gear:['Harpoon']},attention:'AFK',afkWindowSeconds:70,riskType:'SAFE',competitionRisk:'LOW',tags:['shark','fishing','members'],items:['Raw shark']},
  {id:'v4-amethyst',name:'Mine Amethyst',kind:'GATHERING',category:'Mining',skills:['Mining'],f2p:false,members:true,verified,source:'Migrated from verified V2.5 dataset',lastVerified:date,requirements:{skills:[{skill:'Mining',level:92}],areas:['Mining Guild members area']},attention:'AFK',afkWindowSeconds:60,riskType:'SAFE',competitionRisk:'LOW',tags:['amethyst','mining','members'],items:['Amethyst']},

  // V4 catalog placeholders: visible/searchable but intentionally excluded from recommendations until verified.
  {id:'v4-onyx-jewellery',name:'Onyx jewellery chain',kind:'PROCESSING',category:'Crafting',skills:['Crafting','Magic'],f2p:false,members:true,verified:needs,source:'Needs OSRS verification',lastVerified:'',requirements:{},attention:'MEDIUM',riskType:'HIGH_REQUIREMENT',tags:['onyx','ring','necklace','bracelet','amulet','enchant','members'],items:['Onyx'],notes:'V4 catalog target; requirements/economics must be verified before recommendation.'},
  {id:'v4-zenyte-jewellery',name:'Zenyte jewellery chain',kind:'PROCESSING',category:'Crafting',skills:['Crafting','Magic'],f2p:false,members:true,verified:needs,source:'Needs OSRS verification',lastVerified:'',requirements:{},attention:'MEDIUM',riskType:'HIGH_REQUIREMENT',tags:['zenyte','jewellery','enchant','members'],items:['Zenyte'],notes:'Needs verification.'},
  {id:'v4-herblore',name:'Herblore potion processing catalog',kind:'PROCESSING',category:'Herblore',skills:['Herblore'],f2p:false,members:true,verified:needs,source:'Needs OSRS verification',lastVerified:'',requirements:{},attention:'MEDIUM',riskType:'SAFE',tags:['herblore','potion','herbs','unfinished potion'],notes:'Expandable V4 category placeholder.'},
  {id:'v4-farming',name:'Farming economic harvest catalog',kind:'GATHERING',category:'Farming',skills:['Farming'],f2p:false,members:true,verified:needs,source:'Needs OSRS verification',lastVerified:'',requirements:{},attention:'LOW',riskType:'SAFE',tags:['farming','herbs','hops','allotment','fruit'],notes:'Expandable V4 category placeholder.'},
  {id:'v4-hunter',name:'Hunter economic activity catalog',kind:'GATHERING',category:'Hunter',skills:['Hunter'],f2p:false,members:true,verified:needs,source:'Needs OSRS verification',lastVerified:'',requirements:{},attention:'MEDIUM',riskType:'SAFE',tags:['hunter','creature','resource'],notes:'Expandable V4 category placeholder.'},
  {id:'v4-thieving',name:'Thieving economic activity catalog',kind:'GATHERING',category:'Thieving',skills:['Thieving'],f2p:false,members:true,verified:needs,source:'Needs OSRS verification',lastVerified:'',requirements:{},attention:'HIGH',riskType:'DEATH_RISK',tags:['thieving','pickpocket','stall','chest'],notes:'Expandable V4 category placeholder.'},
  {id:'v4-slayer',name:'Slayer money-making catalog',kind:'COMBAT',category:'Slayer',skills:['Slayer','Attack','Strength','Defence','Ranged','Magic','Prayer'],f2p:false,members:true,verified:needs,source:'Needs OSRS verification',lastVerified:'',requirements:{},attention:'HIGH',riskType:'DEATH_RISK',tags:['slayer','combat','monster','members'],notes:'Combat activities will carry supply costs and recommended stats.'},
  {id:'v4-barrows',name:'Barrows',kind:'COMBAT',category:'PvM',skills:['Attack','Strength','Defence','Ranged','Magic','Prayer'],f2p:false,members:true,verified:needs,source:'Needs OSRS verification',lastVerified:'',requirements:{},attention:'HIGH',riskType:'DEATH_RISK',tags:['barrows','boss','pvm','members'],notes:'Not eligible for recommendations until verified requirements and net costs are populated.'},
  {id:'v4-wilderness-bosses',name:'Wilderness bosses',kind:'COMBAT',category:'Wilderness PvM',skills:['Attack','Strength','Defence','Ranged','Magic','Prayer'],f2p:false,members:true,verified:needs,source:'Needs OSRS verification',lastVerified:'',requirements:{},attention:'HIGH',riskType:'WILDERNESS',tags:['wilderness','boss','pvp','pvm','members'],notes:'Always separated from safe Top lists.'}
]
