import type { V4Activity } from '../types'

const base = {kind:'COMBAT' as const, category:'F2P Combat', f2p:true, members:true, verified:'VERIFIED' as const, source:'OSRS combat requirements', lastVerified:'2026-10-04', attention:'MEDIUM' as const, riskType:'SAFE' as const}
export const f2pCombatActivities: V4Activity[] = [
  { ...base, id:'combat-f2p-hill-giants', name:'Hill Giants', skills:['Attack','Strength','Defence'], requirements:{}, tags:['f2p','giant','limpwurt','big bones','safe'], items:['Big bones','Limpwurt root'], combat:{recommendedStats:[{skill:'Attack',level:30},{skill:'Strength',level:30},{skill:'Defence',level:20}],soloGroup:'SOLO',deathRisk:'LOW'} },
  { ...base, id:'combat-f2p-moss-giants', name:'Moss Giants', skills:['Attack','Strength','Defence'], requirements:{}, tags:['f2p','giant','mossy key','safe'], items:['Big bones','Mossy key'], combat:{recommendedStats:[{skill:'Attack',level:40},{skill:'Strength',level:40},{skill:'Defence',level:30}],soloGroup:'SOLO',deathRisk:'LOW'} },
  { ...base, id:'combat-f2p-ankou', name:'Ankous', skills:['Attack','Strength','Defence'], requirements:{}, tags:['f2p','ankou','runes','stronghold','safe'], items:['Death rune','Law rune','Adamant arrow'], combat:{recommendedStats:[{skill:'Attack',level:50},{skill:'Strength',level:50},{skill:'Defence',level:40}],soloGroup:'SOLO',deathRisk:'MEDIUM'} },
  { ...base, id:'combat-f2p-lesser-demons', name:'Lesser Demons', skills:['Attack','Strength','Defence'], requirements:{}, tags:['f2p','demon','rune med','safe'], items:['Rune med helm'], combat:{recommendedStats:[{skill:'Attack',level:50},{skill:'Strength',level:50},{skill:'Defence',level:40}],soloGroup:'SOLO',deathRisk:'MEDIUM'} },
  { ...base, id:'combat-f2p-greater-demons', name:'Greater Demons (Wilderness)', skills:['Attack','Strength','Defence'], requirements:{}, tags:['f2p','demon','wilderness','pvp'], items:['Rune full helm'], riskType:'WILDERNESS', attention:'HIGH', combat:{recommendedStats:[{skill:'Attack',level:60},{skill:'Strength',level:60},{skill:'Defence',level:50}],soloGroup:'SOLO',deathRisk:'HIGH',wildernessPvpRisk:true} },
  { ...base, id:'combat-f2p-ogress', name:'Ogress Warrior / Shaman', skills:['Attack','Strength','Defence','Ranged','Magic'], requirements:{quests:['The Corsair Curse']}, tags:['f2p','ogress','runes','rune items'], items:['Rune items','Runes'], verified:'NEEDS_VERIFICATION', combat:{recommendedStats:[{skill:'Ranged',level:40}],soloGroup:'SOLO',deathRisk:'MEDIUM'} },
]
