import type { V4Activity } from '../types'
const base = {kind:'COMBAT' as const, category:'Boss / PvM', f2p:false, members:true, verified:'VERIFIED' as const, source:'OSRS boss access requirements', lastVerified:'2026-10-04', attention:'HIGH' as const, riskType:'HIGH_REQUIREMENT' as const}
export const p2pBossCombatActivities: V4Activity[] = [
 { ...base,id:'combat-giant-mole',name:'Giant Mole',skills:['Attack','Strength','Defence'],requirements:{},tags:['boss','mole','safe','solo'],items:['Mole skin','Mole claw'],riskType:'SAFE',combat:{recommendedStats:[{skill:'Attack',level:60},{skill:'Strength',level:60},{skill:'Defence',level:50}],soloGroup:'SOLO',deathRisk:'MEDIUM'}},
 { ...base,id:'combat-barrows',name:'Barrows',skills:['Magic','Prayer','Defence'],requirements:{quests:['Priest in Peril']},tags:['barrows','boss','morytania','safe'],items:['Barrows equipment','Runes'],combat:{recommendedStats:[{skill:'Magic',level:70},{skill:'Prayer',level:43},{skill:'Defence',level:50}],soloGroup:'SOLO',deathRisk:'MEDIUM',consumables:['Prayer potions','Runes','Food']}},
 { ...base,id:'combat-zulrah',name:'Zulrah',skills:['Ranged','Magic'],requirements:{quests:['Regicide']},tags:['boss','zulrah','solo'],items:['Zulrah loot'],combat:{recommendedStats:[{skill:'Ranged',level:75},{skill:'Magic',level:75}],soloGroup:'SOLO',deathRisk:'HIGH',consumables:['Food','Potions','Runes/ammunition']}},
 { ...base,id:'combat-vorkath',name:'Vorkath',skills:['Ranged','Defence','Prayer'],requirements:{quests:['Dragon Slayer II']},tags:['boss','vorkath','dragon','solo'],items:['Vorkath loot'],combat:{recommendedStats:[{skill:'Ranged',level:85},{skill:'Defence',level:70},{skill:'Prayer',level:70}],soloGroup:'SOLO',deathRisk:'HIGH',consumables:['Food','Potions','Ammunition','Charges']}},
 { ...base,id:'combat-demonic-gorillas',name:'Demonic Gorillas',skills:['Attack','Strength','Ranged','Prayer'],requirements:{quests:['Monkey Madness II']},tags:['demonic gorilla','zenyte','pvm'],items:['Zenyte shard'],combat:{recommendedStats:[{skill:'Attack',level:75},{skill:'Strength',level:75},{skill:'Ranged',level:75},{skill:'Prayer',level:70}],soloGroup:'SOLO',deathRisk:'HIGH',consumables:['Food','Potions','Ammunition']}},
 { ...base,id:'combat-rune-dragons',name:'Rune Dragons',skills:['Attack','Strength','Defence'],requirements:{quests:['Dragon Slayer II']},tags:['dragon','rune dragon','afk'],items:['Rune dragon loot'],attention:'LOW',afkWindowSeconds:30,combat:{recommendedStats:[{skill:'Attack',level:80},{skill:'Strength',level:80},{skill:'Defence',level:80}],soloGroup:'SOLO',deathRisk:'MEDIUM',consumables:['Food','Potions','Charges']}},
 { ...base,id:'combat-green-dragons-wildy',name:'Green Dragons (Wilderness)',skills:['Attack','Strength','Defence'],requirements:{},tags:['dragon','green dragon','wilderness','pvp'],items:['Dragon bones','Green dragonhide'],riskType:'WILDERNESS',combat:{recommendedStats:[{skill:'Attack',level:60},{skill:'Strength',level:60},{skill:'Defence',level:40}],soloGroup:'SOLO',deathRisk:'HIGH',wildernessPvpRisk:true,consumables:['Food']}},
 { ...base,id:'combat-revenants',name:'Revenants',skills:['Ranged','Attack','Strength'],requirements:{},tags:['revenant','wilderness','pvp'],items:['Revenant loot'],riskType:'PVP',combat:{recommendedStats:[{skill:'Ranged',level:70}],soloGroup:'SOLO',deathRisk:'HIGH',wildernessPvpRisk:true,consumables:['Food','Potions','Ammunition']}},
 { ...base,id:'combat-raids-cox',name:'Chambers of Xeric',skills:['Attack','Strength','Defence','Ranged','Magic','Prayer'],requirements:{},tags:['raid','cox','olm','group','solo'],items:['Raids loot'],verified:'NEEDS_VERIFICATION',combat:{recommendedStats:[{skill:'Attack',level:80},{skill:'Strength',level:80},{skill:'Defence',level:80},{skill:'Ranged',level:80},{skill:'Magic',level:80},{skill:'Prayer',level:70}],soloGroup:'BOTH',deathRisk:'HIGH',consumables:['Supplies','Charges']}},
 { ...base,id:'combat-raids-tob',name:'Theatre of Blood',skills:['Attack','Strength','Defence','Ranged','Magic','Prayer'],requirements:{},tags:['raid','tob','group'],items:['Raids loot'],verified:'NEEDS_VERIFICATION',combat:{recommendedStats:[{skill:'Attack',level:90},{skill:'Strength',level:90},{skill:'Defence',level:80},{skill:'Ranged',level:90},{skill:'Magic',level:90},{skill:'Prayer',level:74}],soloGroup:'GROUP',deathRisk:'HIGH'}},
 { ...base,id:'combat-raids-toa',name:'Tombs of Amascut',skills:['Attack','Strength','Defence','Ranged','Magic','Prayer'],requirements:{quests:['Beneath Cursed Sands']},tags:['raid','toa','group','solo'],items:['Raids loot'],verified:'NEEDS_VERIFICATION',combat:{recommendedStats:[{skill:'Attack',level:75},{skill:'Strength',level:75},{skill:'Defence',level:70},{skill:'Ranged',level:75},{skill:'Magic',level:75},{skill:'Prayer',level:70}],soloGroup:'BOTH',deathRisk:'HIGH'}},
]
