import type { V4Activity } from '../types'
const v='VERIFIED' as const,d='2026-10-04'
export const f2pMagicCombatActivities:V4Activity[]=[
 {id:'f2p-low-alch',name:'Low Level Alchemy',kind:'MAGIC',category:'Magic',skills:['Magic'],f2p:true,members:true,verified:v,source:'OSRS spellbook/F2P economy verification',lastVerified:d,requirements:{skills:[{skill:'Magic',level:21}],gear:['Fire rune source','Nature rune']},attention:'HIGH',riskType:'SAFE',tags:['low alch','alchemy','magic','f2p'],notes:'Economic value depends on live item input price and fixed alchemy value.'},
 {id:'f2p-telegrab',name:'Telekinetic Grab economic pickups',kind:'MAGIC',category:'Magic',skills:['Magic'],f2p:true,members:true,verified:v,source:'OSRS spellbook/F2P economy verification',lastVerified:d,requirements:{skills:[{skill:'Magic',level:33}],gear:['Air rune source','Law rune']},attention:'MEDIUM',riskType:'SAFE',tags:['telegrab','telekinetic grab','wine of zamorak','magic','f2p'],notes:'Specific pickup location may add danger/access; evaluate per activity before recommendation.'},
 {id:'f2p-superheat',name:'Superheat Item',kind:'MAGIC',category:'Magic + Smithing',skills:['Magic','Smithing'],f2p:true,members:true,verified:v,source:'OSRS F2P money guide',lastVerified:d,requirements:{skills:[{skill:'Magic',level:43}]},attention:'HIGH',riskType:'SAFE',tags:['superheat','bar','smithing','magic','f2p'],notes:'Bar-specific Smithing level and ore/coal inputs still apply; use child recipe requirements.'},
 {id:'f2p-high-alch',name:'High Level Alchemy',kind:'MAGIC',category:'Magic',skills:['Magic'],f2p:true,members:true,verified:v,source:'OSRS spellbook/F2P economy verification',lastVerified:d,requirements:{skills:[{skill:'Magic',level:55}],gear:['Fire rune source','Nature rune']},attention:'HIGH',riskType:'SAFE',tags:['high alch','alchemy','magic','f2p'],notes:'Profit must include item purchase price + nature rune and fixed high-alch value.'},
 {id:'f2p-hill-giants',name:'Kill Hill Giants',kind:'COMBAT',category:'F2P Combat',skills:['Attack','Strength','Defence','Hitpoints'],f2p:true,members:true,verified:v,source:'OSRS Wiki F2P money guide',lastVerified:d,requirements:{skills:[{skill:'Attack',level:30},{skill:'Strength',level:30},{skill:'Defence',level:30}]},attention:'MEDIUM',riskType:'DEATH_RISK',tags:['hill giant','big bones','combat','f2p'],notes:'30+ melee stats are guide-level recommendations, not hard monster access requirements. Net GP/h must subtract food/supplies.'},
 {id:'f2p-chaos-dwarves',name:'Kill Chaos Dwarves',kind:'COMBAT',category:'F2P Combat',skills:['Attack','Strength','Defence','Hitpoints'],f2p:true,members:true,verified:v,source:'OSRS Wiki F2P money guide',lastVerified:d,requirements:{skills:[{skill:'Attack',level:40},{skill:'Strength',level:40},{skill:'Defence',level:40}]},attention:'MEDIUM',riskType:'DEATH_RISK',tags:['chaos dwarf','combat','f2p'],notes:'Guide recommends roughly 60+ combat; listed skill levels are conservative planner gate, not an in-game access requirement.'},
]
