import type { V4Activity } from '../types'
const d='2026-10-04', src='OSRS stable Hunter/Thieving requirements; Foundation 5 curated P2P gathering dataset'
export const p2pHunterThievingActivities:V4Activity[]=[
 {id:'p2p-hunter-chinchompa',name:'Hunt Chinchompas',kind:'GATHERING',category:'Hunter',skills:['Hunter'],f2p:false,members:true,verified:'VERIFIED',source:src,lastVerified:d,requirements:{skills:[{skill:'Hunter',level:53}]},attention:'HIGH',riskType:'SAFE',competitionRisk:'MEDIUM',tags:['hunter','chinchompa','p2p'],items:['Chinchompa']},
 {id:'p2p-hunter-red-chinchompa',name:'Hunt Red chinchompas',kind:'GATHERING',category:'Hunter',skills:['Hunter'],f2p:false,members:true,verified:'VERIFIED',source:src,lastVerified:d,requirements:{skills:[{skill:'Hunter',level:63}]},attention:'HIGH',riskType:'SAFE',competitionRisk:'MEDIUM',tags:['hunter','red chinchompa','p2p'],items:['Red chinchompa']},
 {id:'p2p-hunter-black-chinchompa',name:'Hunt Black chinchompas',kind:'GATHERING',category:'Hunter',skills:['Hunter'],f2p:false,members:true,verified:'VERIFIED',source:src,lastVerified:d,requirements:{skills:[{skill:'Hunter',level:73}]},attention:'HIGH',riskType:'WILDERNESS',competitionRisk:'HIGH',tags:['hunter','black chinchompa','wilderness','p2p'],items:['Black chinchompa']},
 {id:'p2p-thieve-master-farmer',name:'Pickpocket Master Farmers',kind:'GATHERING',category:'Thieving',skills:['Thieving'],f2p:false,members:true,verified:'VERIFIED',source:src,lastVerified:d,requirements:{skills:[{skill:'Thieving',level:38}]},attention:'HIGH',riskType:'SAFE',competitionRisk:'LOW',tags:['thieving','master farmer','seeds','p2p'],items:['Seeds'],notes:'Seed output is mixed; use weighted output value. Success rate changes with Thieving level.'},
 {id:'p2p-thieve-ardy-knight',name:'Pickpocket Ardougne Knights',kind:'GATHERING',category:'Thieving',skills:['Thieving'],f2p:false,members:true,verified:'VERIFIED',source:src,lastVerified:d,requirements:{skills:[{skill:'Thieving',level:55}],areas:['Ardougne']},attention:'HIGH',riskType:'SAFE',competitionRisk:'LOW',tags:['thieving','ardougne knight','coins','p2p'],items:['Coins'],notes:'Success rate scales with Thieving level; diary bonuses should be modelled separately.'},
 {id:'p2p-thieve-vyre',name:'Pickpocket Vyres',kind:'GATHERING',category:'Thieving',skills:['Thieving'],f2p:false,members:true,verified:'VERIFIED',source:src,lastVerified:d,requirements:{skills:[{skill:'Thieving',level:82}],quests:['Sins of the Father'],areas:['Darkmeyer']},attention:'HIGH',riskType:'HIGH_REQUIREMENT',competitionRisk:'LOW',tags:['thieving','vyre','blood shard','p2p'],items:['Blood shard'],notes:'Rare-drop method; GP/h requires full loot table rather than Blood shard alone.'},
 {id:'p2p-thieve-elf',name:'Pickpocket Elves',kind:'GATHERING',category:'Thieving',skills:['Thieving'],f2p:false,members:true,verified:'VERIFIED',source:src,lastVerified:d,requirements:{skills:[{skill:'Thieving',level:85}],quests:['Song of the Elves'],areas:['Prifddinas']},attention:'HIGH',riskType:'HIGH_REQUIREMENT',competitionRisk:'LOW',tags:['thieving','elf','enhanced crystal teleport seed','p2p'],items:['Enhanced crystal teleport seed'],notes:'Rare-drop method; expected value must use complete loot distribution.'},
]
