import type { V4Activity } from '../types'
const base = {kind:'COMBAT' as const, category:'Slayer Combat', f2p:false, members:true, verified:'VERIFIED' as const, source:'OSRS Slayer requirements', lastVerified:'2026-10-04', attention:'MEDIUM' as const, riskType:'SAFE' as const}
export const p2pSlayerCombatActivities: V4Activity[] = [
 { ...base,id:'combat-dust-devils',name:'Dust Devils',skills:['Slayer','Magic'],requirements:{skills:[{skill:'Slayer',level:65}]},tags:['slayer','dust devil','barrage','burst'],items:['Slayer loot'],combat:{slayerLevel:65,recommendedStats:[{skill:'Magic',level:70}],soloGroup:'SOLO',deathRisk:'LOW',consumables:['Runes','Prayer potions']}},
 { ...base,id:'combat-kurasks',name:'Kurasks',skills:['Slayer','Ranged','Attack','Strength'],requirements:{skills:[{skill:'Slayer',level:70}],gear:['Leaf-bladed weapon or broad ammunition']},tags:['slayer','kurask','safe'],items:['Kurask loot'],combat:{slayerLevel:70,recommendedStats:[{skill:'Ranged',level:60}],soloGroup:'SOLO',deathRisk:'LOW'}},
 { ...base,id:'combat-skeletal-wyverns',name:'Skeletal Wyverns',skills:['Slayer','Ranged','Defence'],requirements:{skills:[{skill:'Slayer',level:72}],gear:['Elemental/Mind/Dragonfire protection shield']},tags:['slayer','wyvern','dragon'],items:['Wyvern loot'],combat:{slayerLevel:72,recommendedStats:[{skill:'Ranged',level:70},{skill:'Defence',level:60}],soloGroup:'SOLO',deathRisk:'MEDIUM'}},
 { ...base,id:'combat-gargoyles',name:'Gargoyles',skills:['Slayer','Attack','Strength'],requirements:{skills:[{skill:'Slayer',level:75}],gear:['Rock hammer']},tags:['slayer','gargoyle','afk'],items:['Gargoyle loot'],attention:'LOW',afkWindowSeconds:45,combat:{slayerLevel:75,recommendedStats:[{skill:'Attack',level:70},{skill:'Strength',level:70}],soloGroup:'SOLO',deathRisk:'LOW'}},
 { ...base,id:'combat-nechryaels',name:'Nechryaels',skills:['Slayer','Magic'],requirements:{skills:[{skill:'Slayer',level:80}]},tags:['slayer','nechryael','barrage'],items:['Slayer loot'],combat:{slayerLevel:80,recommendedStats:[{skill:'Magic',level:80}],soloGroup:'SOLO',deathRisk:'MEDIUM',consumables:['Runes','Prayer potions']}},
 { ...base,id:'combat-abyssal-demons',name:'Abyssal Demons',skills:['Slayer','Attack','Strength'],requirements:{skills:[{skill:'Slayer',level:85}]},tags:['slayer','abyssal whip','afk'],items:['Abyssal whip','Slayer loot'],attention:'LOW',afkWindowSeconds:45,combat:{slayerLevel:85,recommendedStats:[{skill:'Attack',level:75},{skill:'Strength',level:75}],soloGroup:'SOLO',deathRisk:'LOW'}},
 { ...base,id:'combat-kraken',name:'Kraken',skills:['Slayer','Magic'],requirements:{skills:[{skill:'Slayer',level:87}]},tags:['slayer','boss','kraken','task'],items:['Kraken loot'],riskType:'HIGH_REQUIREMENT',combat:{slayerLevel:87,recommendedStats:[{skill:'Magic',level:75}],soloGroup:'SOLO',deathRisk:'LOW'}},
]
